"""
Django settings for friendship project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9uvv$wt&k9a40q)v5wbr7kbh^jf^9v!(yb9rqj#8+8b=p0w#cc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'content'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'friendship.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'friendship.wsgi.application'

TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 600,
    "menubar": True,
    "browser_spellcheck": True,
    "contextmenu": False,
    "promotion": False,
    "plugins": (
        "accordion advlist anchor autolink autoresize autosave charmap code "
        "codesample directionality emoticons fullscreen help image importcss "
        "insertdatetime link lists media nonbreaking pagebreak preview quickbars "
        "searchreplace table visualblocks visualchars wordcount"
    ),
    "toolbar": (
        "undo redo | blocks fontfamily fontsize | "
        "bold italic underline strikethrough | forecolor backcolor | "
        "alignleft aligncenter alignright alignjustify | "
        "bullist numlist outdent indent | link image media table | "
        "blockquote codesample charmap emoticons | "
        "removeformat searchreplace visualblocks code fullscreen preview help"
    ),
    "toolbar_mode": "sliding",
    "quickbars_selection_toolbar": (
        "bold italic underline | quicklink blockquote"
    ),
    "style_formats_merge": True,
    "style_formats": [
        {
            "title": "Styled link",
            "selector": "a",
            "classes": "styled-link",
        },
    ],
    "link_class_list": [
        {"title": "Styled link", "value": "styled-link"},
        {"title": "Default link", "value": ""},
    ],
    "font_family_formats": (
        "Helvetica=helvetica,arial,sans-serif; "
        "Old London Alternate=OldLondonAlternate,serif; "
        "Arial=arial,helvetica,sans-serif; "
        "Arial Black=arial black,avant garde; "
        "Book Antiqua=book antiqua,palatino; "
        "Courier New=courier new,courier; "
        "Georgia=georgia,palatino; "
        "Impact=impact,chicago; "
        "Tahoma=tahoma,arial,helvetica,sans-serif; "
        "Times New Roman=times new roman,times; "
        "Trebuchet MS=trebuchet ms,geneva; "
        "Verdana=verdana,geneva"
    ),
    "font_css": (
        "https://db.onlinewebfonts.com/c/"
        "39fe060422750c672f65c87ea433856a?family=OldLondonAlternate"
    ),
    "content_css": (
        "https://db.onlinewebfonts.com/c/"
        "39fe060422750c672f65c87ea433856a?family=OldLondonAlternate"
    ),
    "content_style": (
        "body { font-family: Helvetica, Arial, sans-serif; } "
        ".styled-link { color: #ff6347; text-decoration: none; }"
    ),
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    ('assets', BASE_DIR / 'assets'),
]
