# Generated by Django 6.0.8 on 2026-09-30 04:18

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='The title of the show.', max_length=255)),
                ('info', models.TextField(blank=True, help_text='Optional description of the show.')),
                ('date', models.DateField(help_text='The date of the show.')),
                ('start_time', models.IntegerField(choices=[(0, '12 am'), (1, '1 am'), (2, '2 am'), (3, '3 am'), (4, '4 am'), (5, '5 am'), (6, '6 am'), (7, '7 am'), (8, '8 am'), (9, '9 am'), (10, '10 am'), (11, '11am'), (12, '12 pm'), (13, '1 pm'), (14, '2 pm'), (15, '3 pm'), (16, '4 pm'), (17, '5 pm'), (18, '6 pm'), (19, '7 pm'), (20, '8 pm'), (21, '9 pm'), (22, '10 pm'), (23, '11 pm')], help_text='The time the show starts.')),
                ('duration', models.IntegerField(choices=[(1, '1 hour'), (2, '2 hours'), (3, '3 hours'), (4, '4 hours')], default=1, help_text='The duration of the show in hours.')),
                ('start_date_time', models.DateTimeField(editable=False)),
                ('end_date_time', models.DateTimeField(editable=False)),
                ('active', models.BooleanField(default=True, help_text='Controls whether the show appears on the schedule.')),
                ('show_image', models.ImageField(blank=True, max_length=500, upload_to='shows/images/')),
                ('show_flyer', models.ImageField(blank=True, max_length=500, upload_to='shows/images/')),
                ('pre_recorded_show', models.FileField(blank=True, help_text='Optional pre-recorded show. Files must be MP3 format. 128 kbps is recommended.', max_length=500, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/spie/code/sites/friendshipradio.rodeo/uploads')), upload_to='scheduler/')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['active', 'start_date_time', 'end_date_time'], name='show_schedule_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'start_time'), name='unique_show_start_time')],
            },
        ),
    ]
