# Generated by Django 6.0.8 on 2026-08-05 02:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', tinymce.models.HTMLField(blank=True, help_text='Content that will be displayed in the info section of the website', null=True)),
            ],
            options={
                'verbose_name_plural': 'Info / About',
            },
        ),
    ]
