# Generated by Django 6.0.8 on 2026-08-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, help_text='Content that is populated in the marquee', max_length=500, null=True)),
                ('active', models.BooleanField(default=True, help_text='Indicates whether or not the content will show on the marquee')),
            ],
            options={
                'verbose_name_plural': 'Marquee Text',
            },
        ),
    ]
