# Generated by Django 6.0.8 on 2026-08-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_marqueetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='DontateText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, help_text='Content that is populated in the donation context area of the site.', max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Donate Text',
            },
        ),
    ]
