# Generated by Django 6.0.8 on 2026-08-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_dontatetext'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DontateText',
            new_name='DonateText',
        ),
    ]
